spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/renta
    username: cauldron
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: devteamrenta@gmail.com
    password: hezhicarjwlqotzl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


